[user]
ip = ""
local_port = -1
public_port = -1

[server]
ip = "127.0.0.1"
port = 5555

[history]
user_consent = false
path = "/path/to/history"

[ssl]
certificate = "/path/to/certificate"
key = "/path/to/key"